version: "3.0"

services:
  db:
    container_name: postgresql_db
    image: postgres:14.1-alpine
    restart: always
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data:rw

volumes:
  db-data: